config/routes.rb
Rails.application.routes.draw do
  root to: 'people#index'
  get 'dashboard', to: 'dashboard#index'
  get 'filter', to: 'dashboard#filter'
  get 'active_periods/create'
  get 'active_period/create'
  resources :departments do
    member do
      get 'new_name'
      patch 'set_name'
      get 'new_parent'
      patch 'set_parent'
    end
  end
  resources :people
  resources :working_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :working_periods
    has_many :departments, through: :working_periods

    validates :fullname, presence: true

    def working_periods_in_department(department)
        working_periods.where(department: department)
    end

    def department_on_date(department, date)
        if working_periods.overlapping_date(date).present?
            working_periods.overlapping_date(date).last.department
        end
    end

    def assigned_at_department_on_date(department, date)
        if working_periods.overlapping_date(date).present?
            working_periods.overlapping_date(date).last.start_at
        end
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
    @working_periods = @person.working_periods
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:fullname)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="card">
  <div class="card-header">
      <h3 class="mb-0">Create new person</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: person) do |form| %>
      <%= render '/shared/errors', object: person %>
      <div class="field">
        <%= form.label :fullname %>
        <%= form.text_field :fullname, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Create', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/people/_people.html.erb
<table class="table">
    <thead>
        <th><%= t 'model.person.attributes.fullname' %></th>
        <th><%= t 'model.person.attributes.assigned_at' %></th>
    </thead>
    <tbody>
        <%= render @people %>
    </tbody>
</table>

app/views/people/_person.html.erb
<tr>
    <td><%= person.fullname %></td>
    <td><%= person.assigned_at_department_on_date(@department, @date) %></td>
</tr>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= t 'model.person.many' %>
  <%= link_to (t 'xx.new'), new_person_path, class: 'btn btn-success' %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t 'xx.fullname' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.fullname %></td>
        <td><%= link_to (t 'xx.show'), person %></td>
        <td><%= link_to (t 'xx.edit'), edit_person_path(person) %></td>
        <td><%= link_to (t 'xx.destroy'), person, method: :delete, data: { confirm: (t 'xx.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t 'model.person.attributes.fullname' %>:</strong>
  <%= @person.fullname %>
</p>

<div class="btn-group mb-3">
  <%= link_to (t 'people.actions.assign_to_department'), new_working_period_path(person_id: @person), class: 'btn btn-outline-primary' %>
  <%= link_to (t 'xx.edit'), edit_person_path(@person), class: 'btn btn-outline-secondary' %>
  <%= link_to (t 'xx.list'), people_path, class: 'btn btn-outline-secondary' %>
</div>

<%= render 'working_periods/working_periods' %>