config/routes.rb
Rails.application.routes.draw do
  root to: 'people#index'
  get 'dashboard', to: 'dashboard#index'
  get 'filter', to: 'dashboard#filter'
  get 'active_periods/create'
  get 'active_period/create'
  resources :departments do
    member do
      get 'new_name'
      patch 'set_name'
      get 'new_parent'
      patch 'set_parent'
    end
  end
  resources :people
  resources :working_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/working_period.rb
class WorkingPeriod < ApplicationRecord
  belongs_to :department
  belongs_to :person

  validates :start_at, presence: true
  validate :periods_overlaps
  validate :working_only_at_one_department_at_time


	scope :overlapping_date, -> (date) do
    where("start_at <= ? AND (end_at > ? OR end_at IS NULL)", date, date)
	end
  scope :overlapping_with_department, -> (department, date) do
    d_wps = department.working_periods.overlapping_date(date)
    wps = WorkingPeriod.overlapping_date(date)
    d_wps & wps
  end
  default_scope { order(start_at: :asc) }

	def active_timerange
    start_at..(end_at || Date.new(9999,1,1))
  end

  private
    def periods_overlaps
      unless department.active_timerange.cover?(active_timerange)
        txt = %q(
          период работы сотрудника в отделе должен лежать в пределах периода
          существования отдела
        )
        errors.add(:base, txt)
      end
    end

    def working_only_at_one_department_at_time
      if person.working_periods.any?
        if person.working_periods.any?{|wp| wp.active_timerange.overlaps?(active_timerange)}
          txt = %q(
            сотрудник может переходить из отдела в любой момент
            работает только в одном отделе
          )
          errors.add(:base, txt)
        end
      end
    end
end

app/controllers/working_periods_controller.rb
class WorkingPeriodsController < ApplicationController
  before_action :set_working_period, only: %i[ show edit update destroy ]

  # GET /working_periods or /working_periods.json
  def index
    @working_periods = WorkingPeriod.all
  end

  # GET /working_periods/1 or /working_periods/1.json
  def show
  end

  # GET /working_periods/new
  def new
    @working_period = WorkingPeriod.new
    @departments = Department.all
    @people = Person.all
  end

  # GET /working_periods/1/edit
  def edit
  end

  # POST /working_periods or /working_periods.json
  def create
    @working_period = WorkingPeriod.new(working_period_params)

    respond_to do |format|
      if @working_period.save
        format.html { redirect_to @working_period.department, notice: "Working period was successfully created." }
        format.json { render :show, status: :created, location: @working_period }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @working_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /working_periods/1 or /working_periods/1.json
  def update
    respond_to do |format|
      if @working_period.update(working_period_params)
        format.html { redirect_to @working_period.department, notice: "Working period was successfully updated." }
        format.json { render :show, status: :ok, location: @working_period }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @working_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /working_periods/1 or /working_periods/1.json
  def destroy
    @working_period.destroy
    respond_to do |format|
      format.html { redirect_to working_periods_url, notice: "Working period was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_working_period
      @working_period = WorkingPeriod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def working_period_params
      params.require(:working_period).permit(:start_at, :end_at, :department_id, :person_id)
    end
end

app/helpers/working_periods_helper.rb
module WorkingPeriodsHelper
end

app/views/working_periods/_form.html.erb
<div class="card">
  <div class="card-header">
      <h3 class="mb-0">Assign person to department</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: working_period) do |form| %>
      <%= render '/shared/errors', object: working_period %>

      <div class="field">
        <%= form.label :start_at %>
        <%= form.date_field :start_at, required: true %>
      </div>

      <div class="field">
        <%= form.label :end_at %>
        <%= form.date_field :end_at %>
      </div>

      <div class="field">
        <%= form.label :department_id %>
        <%= form.select :department_id, options_from_collection_for_select(@departments, "id", "name", selected: params[:department_id]) %>
      </div>
      
      <div class="field">
        <%= form.label :person_id %>
        <%= form.select :person_id, options_from_collection_for_select(@people, "id", "fullname", selected: params[:person_id]) %>
      </div>

      <div class="actions">
        <%= form.submit 'Assign', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/working_periods/_working_period.html.erb
<tr>
    <td><%= working_period.start_at %></td>
    <td><%= working_period.end_at %></td>
    <td><%= working_period.department_id %></td>
    <td><%= working_period.person_id %></td>
    <td><%= link_to 'Destroy', working_period, method: :delete, data: { confirm: 'Are you sure?' } if working_period.persisted? %></td>

</tr>

app/views/working_periods/_working_periods.html.erb
<div class="card">
  <div class="card-header">
      <h3 class="mb-0"><%= t 'xx.history' %></h3>
  </div>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th><%= t 'model.working_period.attributes.start_at' %></th>
          <th><%= t 'model.working_period.attributes.end_at' %></th>
          <th><%= t 'model.department.one' %></th>
          <th><%= t 'model.person.one' %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= render @working_periods %>
      </tbody>
    </table>
  </div>
</div>

app/views/working_periods/edit.html.erb
<h1>Editing Working Period</h1>

<%= render 'form', working_period: @working_period %>

<%= link_to 'Show', @working_period %> |
<%= link_to 'Back', working_periods_path %>

app/views/working_periods/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'working_periods/working_periods', collection: @working_periods %>
<br>

<%= link_to 'New Working Period', new_working_period_path %>

app/views/working_periods/new.html.erb
<%= render 'form', working_period: @working_period %>

app/views/working_periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @working_period.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @working_period.end_at %>
</p>

<p>
  <strong>Department:</strong>
  <%= @working_period.department_id %>
</p>

<p>
  <strong>Person:</strong>
  <%= @working_period.person_id %>
</p>

<%= link_to 'Edit', edit_working_period_path(@working_period) %> |
<%= link_to 'Back', working_periods_path %>