config/routes.rb
Rails.application.routes.draw do
  root to: 'people#index'
  get 'dashboard', to: 'dashboard#index'
  get 'filter', to: 'dashboard#filter'
  get 'active_periods/create'
  get 'active_period/create'
  resources :departments do
    member do
      get 'new_name'
      patch 'set_name'
      get 'new_parent'
      patch 'set_parent'
    end
  end
  resources :people
  resources :working_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
	#belongs_to :parent, :class_name => 'Department', optional: true
	#has_many :children, :class_name => 'Department', :foreign_key => 'parent_id'
	has_many :active_periods, dependent: :destroy
	has_many :working_periods, dependent: :destroy

	has_paper_trail only: [:name, :parent_id]
	
	validates :name, presence: true
	validates :created_at, presence: true
	validate :overlaps_with_parent_department
	
	scope :overlapping_date, -> (date) do
		#joins(:active_periods).where("active_periods.start_at < ? AND active_periods.end_at IS NULL", date)
		#.or(where("active_periods.start_at < ? AND active_periods.end_at > ?", date, date))
		joins(:active_periods).where("active_periods.start_at <= ? AND (active_periods.end_at IS NULL OR active_periods.end_at > ? )", date, date)
	end

	scope :filter_by_date, -> (date) do
		joins(:active_periods).where("active_periods.start_at <= ? AND (active_periods.end_at IS NULL OR active_periods.end_at > ? )", date, date)
	end
	# отделы, которые существуют на заданную дату
	scope :relevant_on_date, -> (date) do
		active_periods.overlapping_date(date)
	end
	scope :roots, -> (date) do
		where(id: ActivePeriod.overlapping_date(date).roots&.pluck(:department_id))
	end

	after_commit :set_active_period_end_on_disband

	def current_active_period(date = Date.today)
		active_periods.overlapping_date(date).last if active_periods.any? and active_periods.overlapping_date(date).any?
	end

	# название отдела на указанную дату
	def name_on_date(date = Date.today)
		current_active_period(date)&.name
	end

	def parent_id(date = Date.today)
		if active_periods.any?
			if active_periods.overlapping_date(date).any?
				active_periods.overlapping_date(date).first.parent_id
			else
				active_periods.last.parent_id 
			end
		else
			0
		end
	end

	def parent(date = Date.today)
		Department.find_by(id: parent_id(date))
	end

	#def parent(date = Date.today)
	#	if active_periods.overlapping_date(date).any?
	#		aps = active_periods.overlapping_date(date)
	#		Department.find_by(id: aps.last[:department_id])
	#	end
	#end

	def children(date = Date.today)
		aps = ActivePeriod.overlapping_date(date).where(parent_id: id)
		Department.where(id: aps.pluck(:department_id))
	end

	def parent_on_date(date = Date.today)
		if active_periods.overlapping_date(date).any?
			parent = Department.find(current_active_period(date).parent_id)
			parent.name
		else
			"No parent name"
		end
	end

	# период существования 
	def active_timerange
		created_at..(disbanded_at || Date.new(9999,1,1) )
	end

	def people_working_on_date(date = Date.today)
		if working_periods != nil
			wps = working_periods.overlapping_date(date)
			people_ids = wps.pluck(:person_id)
			Person.where(id: people_ids)  # TODO: refactor
		end
	end

	def set_active_period_end_on_disband
		active_periods.last.update(end_at: disbanded_at) if disbanded_at.present? 
	end

	private

	def overlaps_with_parent_department
		if parent
			unless parent.active_timerange.cover?(active_timerange)
				txt = %q(
					период нахождения дочернего отдела в родительском должен лежать в
					пределах периода существования родительского отдела (от даты
					формирования до даты расформирования)
				)
				errors.add(:base, txt)
			end
		end
	end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy new_name set_name new_parent set_parent ]

  def new_name
  end

  def set_name
    date = params[:changed_at]
    current_ap = @department.current_active_period(date)

    if current_ap
      new_ap = @department.active_periods.new(
        start_at: params[:changed_at],
        end_at: current_ap.end_at,
        parent_id: @department.parent_id(params[:changed_at]),
        name: params[:name]
      )
      current_ap.end_at = date

      ActiveRecord::Base.transaction do
        current_ap.save!
        new_ap.save!
      end
    else
      raise 'Date should be whithin department active period'
    end
    
    redirect_to @department
  end

  def new_parent
    @departments = Department.all
  end

  def set_parent
    date = params[:changed_at]
    current_ap = @department.current_active_period(date)
    if current_ap
      new_ap = @department.active_periods.new(
        start_at: params[:changed_at],
        end_at: current_ap.end_at,
        parent_id: params[:parent_id],
        name: @department.name_on_date(params[:changed_at]) #Department.find(params[:parent_id]).name_on_date(params[:changed_at])
      )
      current_ap.end_at = date

      ActiveRecord::Base.transaction do
        current_ap.save!
        new_ap.save!
      end
    else
      raise 'Date should be whithin department active period'
    end

    redirect_to @department
  end

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
    @people = Person.all
    @departments = Department.all
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @department.save! 
          active_period = @department.active_periods.new(
            name: department_params[:name],
            start_at: @department.created_at,
            end_at: department_params[:disbanded_at]
          )
          active_period.save!
          format.html { redirect_to @department, notice: "Department was successfully created." }
          format.json { render :show, status: :created, location: @department }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @department.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:created_at, :disbanded_at, :name, :parent_id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<% people = department.people_working_on_date(@date) %>
<% count = people.nil? ? 0 : people.size %>

<li>
	<%= link_to dashboard_path(department: department, date: @date ), class: "#{'bg-primary' if department.id.to_s == params[:department]}" do %>
		<%= department.name_on_date(@date) %>
		<hr>
		<small><%= t '.people_count' %>: <%= count %></small>
		<small><%= t '.children_count' %>: <%= department.children.size %></small>
	<% end %>
	<% if department.children.any? %>
	<details>
	<summary></summary>
		<nav class="sub-menu">
			<ul>
				<%= render department.children %>
			</ul>
		</nav>
	</details>
	<% end %>
</li>

app/views/departments/_departments.html.erb
<nav class="menu">
  <ul class="pl-0">
    <%= render @departments %>
  </ul>
</nav>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :disbanded_at %>
    <%= form.datetime_select :disbanded_at %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/_form_add.html.erb
<div class="card">
  <div class="card-header">
      <h3 class="mb-0">Create new department</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: department) do |form| %>
      <%= render '/shared/errors', object: department %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :created_at %>
        <%= form.date_field :created_at, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :disbanded_at %>
        <%= form.date_field :disbanded_at, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Create', class: 'btn btn-success' %>
      </div>

    <% end %>
  </div>
</div>

app/views/departments/_form_change_name.erb
<h3>Change name</h3>
<%= form_with(model: department, method: :put) do |form| %>
  <%= render '/shared/errors', object: department %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/_form_edit.html.erb
<div class="card mb-3">
  <div class="card-header">
    <%= @department.name %>
    <%= link_to 'Show', @department, class: 'btn btn-dark' %>
  </div>
  <div class="card-body">
    <%= form_with(model: department) do |form| %>
      <%= render '/shared/errors', object: department %>

      <div class="field">
        <%= form.label :created_at %>
        <%= form.date_field :created_at, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :disbanded_at %>
        <%= form.date_field :disbanded_at, class: 'form-control' %>
      </div>

      <div class="actions btn-group">
        <%= form.submit 'Edit', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/departments/_form_set_name.erb
<div class="card">
  <div class="card-header">
      <h3 class="mb-0">Change department name</h3>
  </div>
  <div class="card-body">
    <%= form_with(url: set_name_department_path(department), method: :patch) do |form| %>
      <%= render '/shared/errors', object: department %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :changed_at %>
        <%= form.date_field :changed_at, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Set', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/departments/_form_set_parent.erb
<div class="card mb-3">
  <div class="card-header">
    Set parent
  </div>
  <div class="card-body">
    <%= form_with(url: set_parent_department_path(department), method: :patch) do |form| %>  <%= render '/shared/errors', object: department %>
      <div class="field">
        <%= form.label :parent_id %>
        <%= form.select :parent_id, options_from_collection_for_select(@departments, "id", "name"), include_blank: 'None', class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :changed_at %>
        <%= form.date_field :changed_at, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>

</div>

app/views/departments/edit.html.erb
<%= render 'form_edit', department: @department %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= t 'xx.departments' %>
  <%= link_to (t 'xx.new'), new_department_path, class: 'btn btn-success' %>
</h1>


<table class="table">
  <thead>
    <tr>
      <th><%= t 'model.department.attributes.name' %></th>
      <th><%= t 'model.department.attributes.parent' %></th>
      <th><%= t 'model.department.attributes.created_at' %></th>
      <th><%= t 'model.department.attributes.disbanded_at' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.parent&.name %></td>
        <td><%= department.created_at %></td>
        <td><%= department.disbanded_at %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<%= render 'form_add', department: @department %>

app/views/departments/new_name.html.erb
<%= render 'form_set_name', department: @department %>

app/views/departments/new_parent.html.erb
<%= render 'form_set_parent', department: @department %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <%= @department.name %>
  </div>
  <div class="card-body">

    <p>
      <strong><%= t 'model.department.attributes.name' %>:</strong>
      <%= @department.name %>
    </p>

    <p>
      <strong><%= t 'model.department.attributes.created_at' %>:</strong>
      <%= @department.created_at %>
    </p>

    <p>
      <strong><%= t 'model.department.attributes.disbanded_at' %>:</strong>
      <%= @department.disbanded_at %>
    </p>

    <p>
      <strong><%= t 'model.department.attributes.parent' %>:</strong>
      <%= @department.parent&.name_on_date(@date) %>
    </p>

  </div>
</div>

<div class="btn-group mb-3" role="group" aria-label="Basic example">
  <%= link_to (t 'xx.new'), new_department_path, class: 'btn btn-outline-success' %>
  <%= link_to (t 'departments.actions.assign_person'), new_working_period_path(department_id: @department), class: 'btn btn-outline-primary' %>
  <%= link_to (t 'departments.actions.set_parent'), new_parent_department_path(@department), class: 'btn btn-outline-secondary' %>
  <%= link_to (t 'departments.actions.set_name'), new_name_department_path(@department), class: 'btn btn-outline-secondary' %>
  <%= link_to (t 'xx.edit'), edit_department_path(@department), class: 'btn btn-outline-secondary' %>
  <%= link_to (t 'xx.list'), departments_path, class: 'btn btn-outline-secondary' %>
</div>

<%= render 'active_periods/active_periods'  %>